title: SBCのサポートサイト
description: SBCが制作したボードゲームのサポートサイトです
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
baseurl: "/sbc_bg"
defaults:
  - scope:
      path: "assets/img"
    value:
      image: true
